language: csharp
solution: Buff-Emoticons.sln

jobs:
  include:
    - dotnet: none
      mono: latest
      install:
        - nuget restore Buff-Emoticons.sln
        - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.5.5_Terraria_1.4.2.3.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.5.5/TShock4.5.5_Terraria_1.4.2.3.zip
        - unzip -jq $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe TShockAPI.dll ../lib
        - cd ..
      script:
        - msbuild /p:Configuration=Debug Buff-Emoticons.sln
    - dotnet: 3.1.100
      mono: none
      install:
        - dotnet restore
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.5.5_Terraria_1.4.2.3.zip
        #- ZIPDIR=TShock.4.5.1.Terraria.1.4.2.1
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.5.5/TShock4.5.5_Terraria_1.4.2.3.zip
        #- unzip -jq $ZIPFILE $ZIPDIR/OTAPI.dll $ZIPDIR/TerrariaServer.exe $ZIPDIR/ServerPlugins/TShockAPI.dll
        - unzip -jq $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe TShockAPI.dll ../lib
        - cd ..
      script:
        - dotnet build -c Debug -f netstandard2.0
