language: csharp
solution: Buff-Emoticons.sln

jobs:
  include:
    - dotnet: none
      mono: latest
      install:
        - nuget restore Buff-Emoticons.sln
        - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre11/TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
        - cd ..
      script:
        - msbuild /p:Configuration=Debug Buff-Emoticons.sln
    - dotnet: 3.1.100
      mono: none
      install:
        - dotnet restore
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre11/TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
        - cd ..
      script:
        - dotnet build -c Debug -f netstandard2.0
